In [2]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import itertools
import os
import random
import multiprocessing
import sys
import subprocess

BIO_LIP_COLUMNS = [
"PDB ID",
"Receptor chain",
"Resolution. '-1.00' stands for lack of resolution information, e.g. for NMR",
"Binding site number code",
"Ligand_ID",
"Ligand_chain",
"Ligand serial number",
"    Binding site residues (with PDB residue numbering)",
"    Binding site residues (with residue re-numbered starting from 1)",
"Catalytic site residues (different sites are separated by ';') (with PDB residue numbering)",
"    Catalytic site residues (different sites are separated by ';') (with residue re-numbered starting from 1)",
"EC number",
"GO terms",
"Binding affinity by manual survey of the original literature. The information in '()' is the PubMed ID",
"Binding affinity provided by the Binding MOAD database. The information in '()' is the ligand information in Binding MOAD",
"Binding affinity provided by the PDBbind-CN database. The information in '()' is the ligand information in PDBbind-CN",
"Binding affinity provided by the BindingDB database",
"UniProt ID",
"PubMed ID",
"Residue sequence number of the ligand (field _atom_site.auth_seq_id in PDBx/mmCIF format)",
"Receptor sequence"]



# now the invalid ligands are stored as strings, written one by one.
INVALID_LIGANDS = ['144', '15P', '1PE', '2F2', '2JC', '3HR', '3SY', '7N5', '7PE', '9JE', 'AAE', 'ABA', 'ACE', 'ACN', 'ACT', 'ACY', 'AZI', 'BAM', 'BCN', 'BCT', 'BDN', 'BEN', 'BME', 'BO3', 'BTB', 'BTC', 'BU1', 'C8E', 'CAD', 'CAQ', 'CBM', 'CCN', 'CIT', 'CL',
'CM', 'CMO', 'CO3', 'CPT', 'CXS', 'D10', 'DEP', 'DIO', 'DMS', 'DN', 'DOD', 'DOX', 'EDO', 'EEE', 'EGL', 'EOH', 'EOX', 'EPE', 'ETF', 'FCY', 'FJO', 'FLC', 'FMT', 'FW5', 'GOL', 'GSH', 'GTT', 'GYF', 'HED', 'IHP', 'IHS', 'IMD', 'IOD', 'IPA', 'IPH',
'LDA', 'MB3', 'MEG', 'MES', 'MLA', 'MLI', 'MOH', 'MPD', 'MRD', 'MSE', 'MYR', 'N', 'NA', 'NH2', 'NH4', 'NHE', 'NO3', 'O4B', 'OHE', 'OLA', 'OLC', 'OMB', 'OME', 'OXA', 'P6G', 'PE3', 'PE4', 'PEG', 'PEO', 'PEP', 'PG0', 'PG4', 'PGE', 'PGR',
'PLM', 'PO4', 'POL', 'POP', 'PVO', 'SAR', 'SCN', 'SEO', 'SEP', 'SIN', 'SO4', 'SPD', 'SPM', 'SR', 'STE', 'STO', 'STU', 'TAR', 'TBU', 'TME', 'TPO', 'TRS', 'UNK', 'UNL', 'UNX', 'UPL', 'URE']


# now with these: SO4, GOL, EDO, PO4, ACT, PEG, DMS, TRS, PGE, PG4, FMT, EPE, MPD, MES, CD, IOD
CRYSTALIZATION_LIGANDS = ['SO4', 'GOL', 'EDO', 'PO4', 'ACT', 'PEG', 'DMS', 'TRS', 'PGE', 'PG4', 'FMT', 'EPE', 'MPD', 'MES', 'CD', 'IOD']

ALL_INVALID_LIGANDS = INVALID_LIGANDS + CRYSTALIZATION_LIGANDS



df = pd.read_csv('/home/iscb/wolfson/hagairavid/LocAlign/BioLiP_nr.txt', sep="\t", header=None, names=BIO_LIP_COLUMNS)
relevant_columns = ["PDB ID", "Receptor chain", "Ligand_ID", "Ligand_chain",'Receptor sequence']
df = df[relevant_columns].astype('str')
print(df.shape)
df = df[~df['Ligand_ID'].str.contains('DNA|RNA|PEPTIDE|NONE|nan', case=False, na=False)]
print(df.shape)
df = df[~df['Ligand_ID'].map(lambda x: x in ALL_INVALID_LIGANDS)]

df = df[~df['Receptor chain'].map(lambda x: len(x)>1)]

print(df.shape)


# df = df[:1000:10]
df = df.reset_index(drop=True)

/tmp/ipykernel_697619/3764246858.py:51: DtypeWarning: Columns (13,14,16) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/home/iscb/wolfson/hagairavid/LocAlign/BioLiP_nr.txt', sep="\t", header=None, names=BIO_LIP_COLUMNS)

(82121, 5)
(64854, 5)
(60098, 5)

In [6]:

import shutil

def cluster_sequences(list_sequences, seqid=1.0, coverage=0.8, covmode='0', path2mmseqstmp=None,
                      path2mmseqs=None, threads=8
                      ):

    # Use a Linux-friendly temp directory (defaults to $TMPDIR or a local folder)
    if path2mmseqstmp is None:
        path2mmseqstmp = os.environ.get('TMPDIR', os.path.join(os.getcwd(), 'tmp_mmseqs'))
    os.makedirs(path2mmseqstmp, exist_ok=True)

    # Resolve mmseqs executable
    if path2mmseqs is None:
        mmseqs_exec = shutil.which('mmseqs')
        if mmseqs_exec is None:
            raise FileNotFoundError(
                "mmseqs executable not found in PATH. Install mmseqs2 (e.g., 'conda install -c bioconda mmseqs2') or pass path2mmseqs explicitly."
            )
        path2mmseqs = mmseqs_exec
    else:
        if not os.path.exists(path2mmseqs):
            raise FileNotFoundError(f"mmseqs executable not found at provided path: {path2mmseqs}")

    rng = np.random.randint(0, high=int(1e6))
    tmp_input = os.path.join(path2mmseqstmp, f'tmp_input_file_{rng}.fasta')
    tmp_output = os.path.join(path2mmseqstmp, f'tmp_output_file_{rng}')

    with open(tmp_input, 'w') as f:
        for k, sequence in enumerate(list_sequences):
            f.write(f'>{k}\n')
            f.write(f'{sequence}\n')

    command = ('{mmseqs} easy-cluster {fasta} {result} {tmp} --threads {threads} --min-seq-id %s -c %s --cov-mode %s' % (
        seqid, coverage, covmode)).format(threads=threads, mmseqs=path2mmseqs, fasta=tmp_input, result=tmp_output, tmp=path2mmseqstmp)
    subprocess.run(command.split(' '), check=True)

    with open(tmp_output + '_rep_seq.fasta', 'r') as f:
        representative_indices = [int(x[1:-1]) for x in f.readlines()[::2]]
    cluster_indices = np.zeros(len(list_sequences), dtype=int)
    table_path = tmp_output + '_cluster.tsv'
    table = pd.read_csv(table_path, sep='\t', header=None).to_numpy(dtype=int)
    for i, j in table:
        if i in representative_indices:
            cluster_indices[j] = representative_indices.index(i)
    # Cleanup temporary files if they exist
    for file in [tmp_output + '_rep_seq.fasta', tmp_output + '_all_seqs.fasta', tmp_output + '_cluster.tsv', tmp_input]:
        try:
            if os.path.exists(file):
                os.remove(file)
        except Exception:
            pass
    return np.array(cluster_indices), np.array(representative_indices)


cluster_indices, representative_indices = cluster_sequences(df['Receptor sequence'].to_list(), seqid=0.7,coverage=0.7)

easy-cluster /home/iscb/wolfson/hagairavid/LocAlign/notebooks/tmp_mmseqs/tmp_input_file_959406.fasta /home/iscb/wolfson/hagairavid/LocAlign/notebooks/tmp_mmseqs/tmp_output_file_959406 /home/iscb/wolfson/hagairavid/LocAlign/notebooks/tmp_mmseqs --threads 8 --min-seq-id 0.7 -c 0.7 --cov-mode 0

MMseqs Version:                     	18.8cc5c
Substitution matrix                 	aa:blosum62.out,nucl:nucleotide.out
Seed substitution matrix            	aa:VTML80.out,nucl:nucleotide.out
Sensitivity                         	4
k-mer length                        	0
Target search mode                  	0
k-score                             	seq:2147483647,prof:2147483647
Alphabet size                       	aa:21,nucl:5
Max sequence length                 	65535
Max results per query               	20
Split database                      	0
Split mode                          	2
Split memory limit                  	0
Coverage threshold                  	0.7
Coverage mode                       	0
Compositional bias                  	1
Compositional bias scale            	1
Diagonal scoring                    	true
Exact k-mer matching                	0
Mask residues                       	1
Mask residues probability           	0.9
Mask lower case residues            	0
Mask lower letter repeating N times 	0
Minimum diagonal score              	15
Selected taxa
Include identical seq. id.          	false
Spaced k-mers                       	1
Preload mode                        	0
Pseudo count a                      	substitution:1.100,context:1.400
Pseudo count b                      	substitution:4.100,context:5.800
Spaced k-mer pattern
Local temporary path
Threads                             	8
Compressed                          	0
Verbosity                           	3
Add backtrace                       	false
Alignment mode                      	3
Alignment mode                      	0
Allow wrapped scoring               	false
E-value threshold                   	0.001
Seq. id. threshold                  	0.7
Min alignment length                	0
Seq. id. mode                       	0
Alternative alignments              	0
Max reject                          	2147483647
Max accept                          	2147483647
Score bias                          	0
Realign hits                        	false
Realign score bias                  	-0.2
Realign max seqs                    	2147483647
Correlation score weight            	0
Gap open cost                       	aa:11,nucl:5
Gap extension cost                  	aa:1,nucl:2
Zdrop                               	40
Rescore mode                        	0
Remove hits by seq. id. and coverage	false
Sort results                        	0
Cluster mode                        	0
Max connected component depth       	1000
Similarity type                     	2
Weight file name
Cluster Weight threshold            	0.9
Single step clustering              	false
Cascaded clustering steps           	3
Cluster reassign                    	false
Remove temporary files              	true
Force restart with latest tmp       	false
MPI runner
k-mers per sequence                 	21
Scale k-mers per sequence           	aa:0.000,nucl:0.200
Adjust k-mer length                 	false
Shift hash                          	67
Include only extendable             	false
Skip repeating k-mers               	false
Database type                       	0
Shuffle input database              	true
Createdb mode                       	1
Write lookup file                   	0
Offset of numeric ids               	0
Use GPU                             	0

createdb /home/iscb/wolfson/hagairavid/LocAlign/notebooks/tmp_mmseqs/tmp_input_file_959406.fasta /home/iscb/wolfson/hagairavid/LocAlign/notebooks/tmp_mmseqs/16309752151635879701/input --createdb-mode 1 --write-lookup 0 --threads 8

Shuffle database cannot be combined with --createdb-mode 1
We recompute with --shuffle 0
Converting sequences
[======
Time for merging to input_h: 0h 0m 0s 3ms
Time for merging to input: 0h 0m 0s 2ms
Database type: Aminoacid
Time for processing: 0h 0m 0s 69ms
Create directory /home/iscb/wolfson/hagairavid/LocAlign/notebooks/tmp_mmseqs/16309752151635879701/clu_tmp
cluster /home/iscb/wolfson/hagairavid/LocAlign/notebooks/tmp_mmseqs/16309752151635879701/input /home/iscb/wolfson/hagairavid/LocAlign/notebooks/tmp_mmseqs/16309752151635879701/clu /home/iscb/wolfson/hagairavid/LocAlign/notebooks/tmp_mmseqs/16309752151635879701/clu_tmp --max-seqs 20 -c 0.7 --cov-mode 0 --spaced-kmer-mode 1 --threads 8 --alignment-mode 3 -e 0.001 --min-seq-id 0.7 --remove-tmp-files 1

Set cluster sensitivity to -s 1.000000
Set cluster mode SET COVER
Set cluster iterations to 1
linclust /home/iscb/wolfson/hagairavid/LocAlign/notebooks/tmp_mmseqs/16309752151635879701/input /home/iscb/wolfson/hagairavid/LocAlign/notebooks/tmp_mmseqs/16309752151635879701/clu_tmp/4652526158002022512/clu_redundancy /home/iscb/wolfson/hagairavid/LocAlign/notebooks/tmp_mmseqs/16309752151635879701/clu_tmp/4652526158002022512/linclust --cluster-mode 0 --max-iterations 1000 --similarity-type 2 --threads 8 --compressed 0 -v 3 --cluster-weight-threshold 0.9 --sub-mat 'aa:blosum62.out,nucl:nucleotide.out' -a 0 --alignment-mode 3 --alignment-output-mode 0 --wrapped-scoring 0 -e 0.001 --min-seq-id 0.7 --min-aln-len 0 --seq-id-mode 0 --alt-ali 0 -c 0.7 --cov-mode 0 --max-seq-len 65535 --comp-bias-corr 1 --comp-bias-corr-scale 1 --max-rejected 2147483647 --max-accept 2147483647 --add-self-matches 0 --db-load-mode 0 --pca substitution:1.100,context:1.400 --pcb substitution:4.100,context:5.800 --score-bias 0 --realign 0 --realign-score-bias -0.2 --realign-max-seqs 2147483647 --corr-score-weight 0 --gap-open aa:11,nucl:5 --gap-extend aa:1,nucl:2 --zdrop 40 --alph-size aa:13,nucl:5 --kmer-per-seq 21 --spaced-kmer-mode 1 --kmer-per-seq-scale aa:0.000,nucl:0.200 --adjust-kmer-len 0 --mask 0 --mask-prob 0.9 --mask-lower-case 0 --mask-n-repeat 0 -k 0 --hash-shift 67 --split-memory-limit 0 --include-only-extendable 0 --ignore-multi-kmer 0 --rescore-mode 0 --filter-hits 0 --sort-results 0 --remove-tmp-files 1 --force-reuse 0

kmermatcher /home/iscb/wolfson/hagairavid/LocAlign/notebooks/tmp_mmseqs/16309752151635879701/input /home/iscb/wolfson/hagairavid/LocAlign/notebooks/tmp_mmseqs/16309752151635879701/clu_tmp/4652526158002022512/linclust/17771198253582811241/pref --sub-mat 'aa:blosum62.out,nucl:nucleotide.out' --alph-size aa:13,nucl:5 --min-seq-id 0.7 --kmer-per-seq 21 --spaced-kmer-mode 1 --kmer-per-seq-scale aa:0.000,nucl:0.200 --adjust-kmer-len 0 --mask 0 --mask-prob 0.9 --mask-lower-case 0 --mask-n-repeat 0 --cov-mode 0 -k 0 -c 0.7 --max-seq-len 65535 --hash-shift 67 --split-memory-limit 0 --include-only-extendable 0 --ignore-multi-kmer 0 --threads 8 --compressed 0 -v 3 --cluster-weight-threshold 0.9

kmermatcher /home/iscb/wolfson/hagairavid/LocAlign/notebooks/tmp_mmseqs/16309752151635879701/input /home/iscb/wolfson/hagairavid/LocAlign/notebooks/tmp_mmseqs/16309752151635879701/clu_tmp/4652526158002022512/linclust/17771198253582811241/pref --sub-mat 'aa:blosum62.out,nucl:nucleotide.out' --alph-size aa:13,nucl:5 --min-seq-id 0.7 --kmer-per-seq 21 --spaced-kmer-mode 1 --kmer-per-seq-scale aa:0.000,nucl:0.200 --adjust-kmer-len 0 --mask 0 --mask-prob 0.9 --mask-lower-case 0 --mask-n-repeat 0 --cov-mode 0 -k 0 -c 0.7 --max-seq-len 65535 --hash-shift 67 --split-memory-limit 0 --include-only-extendable 0 --ignore-multi-kmer 0 --threads 8 --compressed 0 -v 3 --cluster-weight-threshold 0.9

Database size: 60098 type: Aminoacid
Reduced amino acid alphabet: (A S T) (C) (D B N) (E Q Z) (F Y) (G) (H) (I V) (K R) (L J M) (P) (W) (X)

Generate k-mers list for 1 split
[=================================================================kmermatcher /home/iscb/wolfson/hagairavid/LocAlign/notebooks/tmp_mmseqs/16309752151635879701/input /home/iscb/wolfson/hagairavid/LocAlign/notebooks/tmp_mmseqs/16309752151635879701/clu_tmp/4652526158002022512/linclust/17771198253582811241/pref --sub-mat 'aa:blosum62.out,nucl:nucleotide.out' --alph-size aa:13,nucl:5 --min-seq-id 0.7 --kmer-per-seq 21 --spaced-kmer-mode 1 --kmer-per-seq-scale aa:0.000,nucl:0.200 --adjust-kmer-len 0 --mask 0 --mask-prob 0.9 --mask-lower-case 0 --mask-n-repeat 0 --cov-mode 0 -k 0 -c 0.7 --max-seq-len 65535 --hash-shift 67 --split-memory-limit 0 --include-only-extendable 0 --ignore-multi-kmer 0 --threads 8 --compressed 0 -v 3 --cluster-weight-threshold 0.9

kmermatcher /home/iscb/wolfson/hagairavid/LocAlign/notebooks/tmp_mmseqs/16309752151635879701/input /home/iscb/wolfson/hagairavid/LocAlign/notebooks/tmp_mmseqs/16309752151635879701/clu_tmp/4652526158002022512/linclust/17771198253582811241/pref --sub-mat 'aa:blosum62.out,nucl:nucleotide.out' --alph-size aa:13,nucl:5 --min-seq-id 0.7 --kmer-per-seq 21 --spaced-kmer-mode 1 --kmer-per-seq-scale aa:0.000,nucl:0.200 --adjust-kmer-len 0 --mask 0 --mask-prob 0.9 --mask-lower-case 0 --mask-n-repeat 0 --cov-mode 0 -k 0 -c 0.7 --max-seq-len 65535 --hash-shift 67 --split-memory-limit 0 --include-only-extendable 0 --ignore-multi-kmer 0 --threads 8 --compressed 0 -v 3 --cluster-weight-threshold 0.9

Database size: 60098 type: Aminoacid
Reduced amino acid alphabet: (A S T) (C) (D B N) (E Q Z) (F Y) (G) (H) (I V) (K R) (L J M) (P) (W) (X)

Generate k-mers list for 1 split
[=================================================================] 60.10K 0s 128ms
Sort kmer 0h 0m 0s 25ms
Sort by rep. sequence 0h 0m 0s 16ms
Time for fill: 0h 0m 0s 10ms
Time for merging to pref: 0h 0m 0s 3ms
Time for processing: 0h 0m 0s 324ms
rescorediagonal /home/iscb/wolfson/hagairavid/LocAlign/notebooks/tmp_mmseqs/16309752151635879701/input /home/iscb/wolfson/hagairavid/LocAlign/notebooks/tmp_mmseqs/16309752151635879701/input /home/iscb/wolfson/hagairavid/LocAlign/notebooks/tmp_mmseqs/16309752151635879701/clu_tmp/4652526158002022512/linclust/17771198253582811241/pref /home/iscb/wolfson/hagairavid/LocAlign/notebooks/tmp_mmseqs/16309752151635879701/clu_tmp/4652526158002022512/linclust/17771198253582811241/pref_rescore1 --sub-mat 'aa:blosum62.out,nucl:nucleotide.out' --rescore-mode 0 --wrapped-scoring 0 --filter-hits 0 -e 0.001 -c 0.7 -a 0 --cov-mode 0 --min-seq-id 0.7 --min-aln-len 0 --seq-id-mode 0 --add-self-matches 0 --sort-results 0 --db-load-mode 0 --threads 8 --compressed 0 -v 3

[=================================================================] 60.10K 0s 128ms
Sort kmer 0h 0m 0s 25ms
Sort by rep. sequence 0h 0m 0s 16ms
Time for fill: 0h 0m 0s 10ms
Time for merging to pref: 0h 0m 0s 3ms
Time for processing: 0h 0m 0s 324ms
rescorediagonal /home/iscb/wolfson/hagairavid/LocAlign/notebooks/tmp_mmseqs/16309752151635879701/input /home/iscb/wolfson/hagairavid/LocAlign/notebooks/tmp_mmseqs/16309752151635879701/input /home/iscb/wolfson/hagairavid/LocAlign/notebooks/tmp_mmseqs/16309752151635879701/clu_tmp/4652526158002022512/linclust/17771198253582811241/pref /home/iscb/wolfson/hagairavid/LocAlign/notebooks/tmp_mmseqs/16309752151635879701/clu_tmp/4652526158002022512/linclust/17771198253582811241/pref_rescore1 --sub-mat 'aa:blosum62.out,nucl:nucleotide.out' --rescore-mode 0 --wrapped-scoring 0 --filter-hits 0 -e 0.001 -c 0.7 -a 0 --cov-mode 0 --min-seq-id 0.7 --min-aln-len 0 --seq-id-mode 0 --add-self-matches 0 --sort-results 0 --db-load-mode 0 --threads 8 --compressed 0 -v 3

[=================================================================] 60.10K 0s 43ms
Time for merging to pref_rescore1: 0h 0m 0s 49ms
Time for processing: 0h 0m 0s 197ms
clust /home/iscb/wolfson/hagairavid/LocAlign/notebooks/tmp_mmseqs/16309752151635879701/input /home/iscb/wolfson/hagairavid/LocAlign/notebooks/tmp_mmseqs/16309752151635879701/clu_tmp/4652526158002022512/linclust/17771198253582811241/pref_rescore1 /home/iscb/wolfson/hagairavid/LocAlign/notebooks/tmp_mmseqs/16309752151635879701/clu_tmp/4652526158002022512/linclust/17771198253582811241/pre_clust --cluster-mode 0 --max-iterations 1000 --similarity-type 2 --threads 8 --compressed 0 -v 3 --cluster-weight-threshold 0.9

Clustering mode: Set Cover
[=================================================================] 60.10K 0s 4ms
Sort entries
Find missing connections
Found 38757 new connections.
Reconstruct initial order
[=================================================================] 60.10K 0s 4ms
Add missing connections
[=================================================================] 60.10K 0s 2ms

Time for read in: 0h 0m 0s 30ms
Total time: 0h 0m 0s 36ms

Size of the sequence database: 60098
Size of the alignment database: 60098
Number of clusters: 27424

Writing results 0h 0m 0s 7ms
Time for merging to pre_clust: 0h 0m 0s 3ms
Time for processing: 0h 0m 0s 70ms
] 60.10K 0s 43ms
Time for merging to pref_rescore1: 0h 0m 0s 49ms
Time for processing: 0h 0m 0s 197ms
clust /home/iscb/wolfson/hagairavid/LocAlign/notebooks/tmp_mmseqs/16309752151635879701/input /home/iscb/wolfson/hagairavid/LocAlign/notebooks/tmp_mmseqs/16309752151635879701/clu_tmp/4652526158002022512/linclust/17771198253582811241/pref_rescore1 /home/iscb/wolfson/hagairavid/LocAlign/notebooks/tmp_mmseqs/16309752151635879701/clu_tmp/4652526158002022512/linclust/17771198253582811241/pre_clust --cluster-mode 0 --max-iterations 1000 --similarity-type 2 --threads 8 --compressed 0 -v 3 --cluster-weight-threshold 0.9

Clustering mode: Set Cover
[=================================================================] 60.10K 0s 4ms
Sort entries
Find missing connections
Found 38757 new connections.
Reconstruct initial order
[=================================================================] 60.10K 0s 4ms
Add missing connections
[=================================================================] 60.10K 0s 2ms

Time for read in: 0h 0m 0s 30ms
Total time: 0h 0m 0s 36ms

Size of the sequence database: 60098
Size of the alignment database: 60098
Number of clusters: 27424

Writing results 0h 0m 0s 7ms
Time for merging to pre_clust: 0h 0m 0s 3ms
Time for processing: 0h 0m 0s 70ms
createsubdb /home/iscb/wolfson/hagairavid/LocAlign/notebooks/tmp_mmseqs/16309752151635879701/clu_tmp/4652526158002022512/linclust/17771198253582811241/order_redundancy /home/iscb/wolfson/hagairavid/LocAlign/notebooks/tmp_mmseqs/16309752151635879701/input /home/iscb/wolfson/hagairavid/LocAlign/notebooks/tmp_mmseqs/16309752151635879701/clu_tmp/4652526158002022512/linclust/17771198253582811241/input_step_redundancy -v 3 --subdb-mode 1

Time for merging to input_step_redundancy: 0h 0m 0s 3ms
Time for processing: 0h 0m 0s 26ms
createsubdb /home/iscb/wolfson/hagairavid/LocAlign/notebooks/tmp_mmseqs/16309752151635879701/clu_tmp/4652526158002022512/linclust/17771198253582811241/order_redundancy /home/iscb/wolfson/hagairavid/LocAlign/notebooks/tmp_mmseqs/16309752151635879701/clu_tmp/4652526158002022512/linclust/17771198253582811241/pref /home/iscb/wolfson/hagairavid/LocAlign/notebooks/tmp_mmseqs/16309752151635879701/clu_tmp/4652526158002022512/linclust/17771198253582811241/pref_filter1 -v 3 --subdb-mode 1

Time for merging to pref_filter1: 0h 0m 0s 3ms
Time for processing: 0h 0m 0s 28ms
filterdb /home/iscb/wolfson/hagairavid/LocAlign/notebooks/tmp_mmseqs/16309752151635879701/clu_tmp/4652526158002022512/linclust/17771198253582811241/pref_filter1 /home/iscb/wolfson/hagairavid/LocAlign/notebooks/tmp_mmseqs/16309752151635879701/clu_tmp/4652526158002022512/linclust/17771198253582811241/pref_filter2 --filter-file /home/iscb/wolfson/hagairavid/LocAlign/notebooks/tmp_mmseqs/16309752151635879701/clu_tmp/4652526158002022512/linclust/17771198253582811241/order_redundancy --threads 8 --compressed 0 -v 3

Filtering using file(s)
[=================================================================] 27.42K 0s 8ms
Time for merging to pref_filter2: 0h 0m 0s 38ms
Time for processing: 0h 0m 0s 121ms
createsubdb /home/iscb/wolfson/hagairavid/LocAlign/notebooks/tmp_mmseqs/16309752151635879701/clu_tmp/4652526158002022512/linclust/17771198253582811241/order_redundancy /home/iscb/wolfson/hagairavid/LocAlign/notebooks/tmp_mmseqs/16309752151635879701/input /home/iscb/wolfson/hagairavid/LocAlign/notebooks/tmp_mmseqs/16309752151635879701/clu_tmp/4652526158002022512/linclust/17771198253582811241/input_step_redundancy -v 3 --subdb-mode 1

Time for merging to input_step_redundancy: 0h 0m 0s 3ms
Time for processing: 0h 0m 0s 26ms
createsubdb /home/iscb/wolfson/hagairavid/LocAlign/notebooks/tmp_mmseqs/16309752151635879701/clu_tmp/4652526158002022512/linclust/17771198253582811241/order_redundancy /home/iscb/wolfson/hagairavid/LocAlign/notebooks/tmp_mmseqs/16309752151635879701/clu_tmp/4652526158002022512/linclust/17771198253582811241/pref /home/iscb/wolfson/hagairavid/LocAlign/notebooks/tmp_mmseqs/16309752151635879701/clu_tmp/4652526158002022512/linclust/17771198253582811241/pref_filter1 -v 3 --subdb-mode 1

Time for merging to pref_filter1: 0h 0m 0s 3ms
Time for processing: 0h 0m 0s 28ms
filterdb /home/iscb/wolfson/hagairavid/LocAlign/notebooks/tmp_mmseqs/16309752151635879701/clu_tmp/4652526158002022512/linclust/17771198253582811241/pref_filter1 /home/iscb/wolfson/hagairavid/LocAlign/notebooks/tmp_mmseqs/16309752151635879701/clu_tmp/4652526158002022512/linclust/17771198253582811241/pref_filter2 --filter-file /home/iscb/wolfson/hagairavid/LocAlign/notebooks/tmp_mmseqs/16309752151635879701/clu_tmp/4652526158002022512/linclust/17771198253582811241/order_redundancy --threads 8 --compressed 0 -v 3

Filtering using file(s)
[=================================================================] 27.42K 0s 8ms
Time for merging to pref_filter2: 0h 0m 0s 38ms
Time for processing: 0h 0m 0s 121ms
rescorediagonal /home/iscb/wolfson/hagairavid/LocAlign/notebooks/tmp_mmseqs/16309752151635879701/clu_tmp/4652526158002022512/linclust/17771198253582811241/input_step_redundancy /home/iscb/wolfson/hagairavid/LocAlign/notebooks/tmp_mmseqs/16309752151635879701/clu_tmp/4652526158002022512/linclust/17771198253582811241/input_step_redundancy /home/iscb/wolfson/hagairavid/LocAlign/notebooks/tmp_mmseqs/16309752151635879701/clu_tmp/4652526158002022512/linclust/17771198253582811241/pref_filter2 /home/iscb/wolfson/hagairavid/LocAlign/notebooks/tmp_mmseqs/16309752151635879701/clu_tmp/4652526158002022512/linclust/17771198253582811241/pref_rescore2 --sub-mat 'aa:blosum62.out,nucl:nucleotide.out' --rescore-mode 1 --wrapped-scoring 0 --filter-hits 1 -e 0.001 -c 0.7 -a 0 --cov-mode 0 --min-seq-id 0.7 --min-aln-len 0 --seq-id-mode 0 --add-self-matches 0 --sort-results 0 --db-load-mode 0 --threads 8 --compressed 0 -v 3

[=================================================================] 27.42K 0s 14ms
Time for merging to pref_rescore2: 0h 0m 0s 33ms
Time for processing: 0h 0m 0s 103ms
align /home/iscb/wolfson/hagairavid/LocAlign/notebooks/tmp_mmseqs/16309752151635879701/clu_tmp/4652526158002022512/linclust/17771198253582811241/input_step_redundancy /home/iscb/wolfson/hagairavid/LocAlign/notebooks/tmp_mmseqs/16309752151635879701/clu_tmp/4652526158002022512/linclust/17771198253582811241/input_step_redundancy /home/iscb/wolfson/hagairavid/LocAlign/notebooks/tmp_mmseqs/16309752151635879701/clu_tmp/4652526158002022512/linclust/17771198253582811241/pref_rescore2 /home/iscb/wolfson/hagairavid/LocAlign/notebooks/tmp_mmseqs/16309752151635879701/clu_tmp/4652526158002022512/linclust/17771198253582811241/aln --sub-mat 'aa:blosum62.out,nucl:nucleotide.out' -a 0 --alignment-mode 3 --alignment-output-mode 0 --wrapped-scoring 0 -e 0.001 --min-seq-id 0.7 --min-aln-len 0 --seq-id-mode 0 --alt-ali 0 -c 0.7 --cov-mode 0 --max-seq-len 65535 --comp-bias-corr 1 --comp-bias-corr-scale 1 --max-rejected 2147483647 --max-accept 2147483647 --add-self-matches 0 --db-load-mode 0 --pca substitution:1.100,context:1.400 --pcb substitution:4.100,context:5.800 --score-bias 0 --realign 0 --realign-score-bias -0.2 --realign-max-seqs 2147483647 --corr-score-weight 0 --gap-open aa:11,nucl:5 --gap-extend aa:1,nucl:2 --zdrop 40 --threads 8 --compressed 0 -v 3

Compute score, coverage and sequence identity

In [9]:
df_nr = df.iloc[representative_indices].reset_index(drop=True)
df_nr = df_nr.drop(columns=['Receptor sequence','Ligand_chain']).rename(columns={'PDB ID':'tar_protein',
                                                                         'Receptor chain':'tar_chain',
                                                                         'Ligand_ID':'tar_ligand',
                                                                         'Ligand_all':'ligand_all'})
df_nr['tar_motif'] = [None for _ in range(len(df_nr))]
df_nr['pocket_residue_ids'] = [None for _ in range(len(df_nr))]  # Will be populated later
df_nr = df_nr[ ['tar_ligand','tar_protein','tar_chain','tar_motif','pocket_residue_ids'] ]
# Don't save yet - will save after populating pocket_residue_ids
print(f"Created df_nr with {len(df_nr)} entries. Ready to extract pocket residues.")

Created df_nr with 23698 entries. Ready to extract pocket residues.

In [10]:
df_nr

      tar_ligand tar_protein tar_chain tar_motif pocket_residue_ids
0            ASN        11as         A      None               None
1            UPA        11ba         A      None               None
2            ADP        13pk         A      None               None
3            HEM        19hc         A      None               None
4            IPM        1a05         A      None               None
...          ...         ...       ...       ...                ...
23693         CA        8haw         A      None               None
23694        G2P        8hbf         A      None               None
23695        HEM        8hbh         B      None               None
23696        ATP        8hbw         A      None               None
23697        MAN        8hc0         A      None               None

[23698 rows x 5 columns]

In [13]:
import sys
sys.path.append('../')

from miners.objects import Protein
from multiprocessing import Pool, cpu_count


def get_pocket_residue_ids(protein_name: str, chain: str, ligand: str, ligand_res_idx: int = 0, distance_thresh: float = 4.0) -> list[int]:
    """
    Extract pocket residue IDs for a given protein-chain-ligand combination.
    Aggregates across all ligand residues (if multiple) and returns a single
    flat, sorted list of unique residue IDs.
    
    Args:
        protein_name: PDB protein name (e.g., '1gkm')
        chain: Chain identifier (e.g., 'A')
        ligand: Ligand identifier (e.g., 'general', 'ADP', etc.)
        ligand_res_idx: Ignored; kept for backward compatibility
        distance_thresh: Pocket cutoff in Å (default: 4.0)
    
    Returns:
        List of residue IDs in the pocket (unique, sorted)
    """
    try:
        protein = Protein(protein_name, chain, ligand, save_models=False)
        ligand_residues = protein.get_ligand_residues()
        pockets = set()
        for i in range(len(ligand_residues)):
            ids = protein.get_pocket_residue_ids(distance_thresh=distance_thresh, ligand_res_idx=i)
            for rid in ids:
                try:
                    pockets.add(int(rid))
                except Exception:
                    pockets.add(rid)
        return sorted(pockets) if pockets else None
    except Exception as e:
        print(f"Error getting pocket for {protein_name} chain {chain} ligand {ligand}: {e}")
        return None


def compute_pocket_for_tuple(args_tuple: tuple[str, str, str], distance_thresh: float = 4.0) -> tuple[list[int] | None, int]:
    """
    Multiprocessing-safe wrapper to compute pocket residue IDs aggregating over
    all ligand residues for a given protein/chain/ligand.
    Returns (sorted_pocket_ids_or_None, ligand_residue_count).
    """
    protein_name, chain, ligand = args_tuple
    try:
        protein = Protein(protein_name, chain, ligand, save_models=False)
        ligand_residues = protein.get_ligand_residues()
        residue_count = len(ligand_residues)
        pockets = set()
        for i in range(residue_count):
            ids = protein.get_pocket_residue_ids(distance_thresh=distance_thresh, ligand_res_idx=i)
            for rid in ids:
                try:
                    pockets.add(int(rid))
                except Exception:
                    pockets.add(rid)
        return (sorted(pockets) if pockets else None), residue_count
    except Exception as e:
        print(f"Error (MP) processing {protein_name} {chain} {ligand}: {e}")
        return None, 0

# Quick test
test_pockets, test_count = compute_pocket_for_tuple(('1gkm', 'A', 'general'))
print(f"Test pockets: {test_pockets} | ligand residues: {test_count}")

Error (MP) processing 1gkm A general: 'A'
Test pockets: None | ligand residues: 0

In [14]:
# Apply pocket residue extraction to all proteins in df_nr (multiprocessing)
print(f"Processing {len(df_nr)} proteins to extract pocket residues (multiprocessing)...")

args_list = [(row['tar_protein'], row['tar_chain'], row['tar_ligand']) for _, row in df_nr.iterrows()]
pocket_residues_list = []
ligand_residue_counts = []

if args_list:
    processes = min(len(args_list), max(1, cpu_count() - 1))
    with Pool(processes=processes) as pool:
        # Preserve order using imap
        for i, (pockets, count) in enumerate(pool.imap(compute_pocket_for_tuple, args_list), 1):
            pocket_residues_list.append(pockets)
            ligand_residue_counts.append(count)
            if i % 50 == 0:
                print(f"Progress: {i}/{len(args_list)}")

# Set columns: tar_motif equals pocket_residue_ids, add ligand residue count
df_nr['pocket_residue_ids'] = pocket_residues_list
df_nr['tar_motif'] = df_nr['pocket_residue_ids']
df_nr['num_ligand_residues'] = ligand_residue_counts

multi_res_cases = (df_nr['num_ligand_residues'] > 1).sum()
print(f"\nCompleted! Added pocket_residue_ids, tar_motif, num_ligand_residues. Multi-residue cases: {multi_res_cases}")
print(f"Sample row: {df_nr.iloc[0]}")

Processing 23698 proteins to extract pocket residues (multiprocessing)...
Progress: 50/23698
Progress: 50/23698
Progress: 100/23698
Progress: 100/23698
Progress: 150/23698
Progress: 150/23698
Progress: 200/23698
Progress: 200/23698
Progress: 250/23698
Progress: 250/23698
Progress: 300/23698
Progress: 350/23698
Progress: 300/23698
Progress: 350/23698
Progress: 400/23698
Progress: 450/23698
Progress: 500/23698
Progress: 550/23698
Progress: 600/23698
Progress: 650/23698
Progress: 700/23698
Progress: 750/23698
Progress: 800/23698
Progress: 400/23698
Progress: 450/23698
Progress: 500/23698
Progress: 550/23698
Progress: 600/23698
Progress: 650/23698
Progress: 700/23698
Progress: 750/23698
Progress: 800/23698
Progress: 850/23698
Progress: 900/23698
Progress: 950/23698
Progress: 1000/23698
Progress: 850/23698
Progress: 900/23698
Progress: 950/23698
Progress: 1000/23698
Progress: 1050/23698
Progress: 1100/23698
Progress: 1150/23698
Progress: 1200/23698
Progress: 1250/23698
Progress: 1300/23698
Progress: 1350/23698
Progress: 1400/23698
Progress: 1450/23698
Progress: 1500/23698
Progress: 1550/23698
Progress: 1600/23698
Progress: 1650/23698
Progress: 1700/23698
Progress: 1750/23698
Progress: 1800/23698
Progress: 1050/23698
Progress: 1100/23698
Progress: 1150/23698
Progress: 1200/23698
Progress: 1250/23698
Progress: 1300/23698
Progress: 1350/23698
Progress: 1400/23698
Progress: 1450/23698
Progress: 1500/23698
Progress: 1550/23698
Progress: 1600/23698
Progress: 1650/23698
Progress: 1700/23698
Progress: 1750/23698
Progress: 1800/23698
Progress: 1850/23698
Progress: 1850/23698
Error (MP) processing 2a9n M ORE: 'M'
Error (MP) processing 2a9n M ORE: 'M'
Progress: 1900/23698
Progress: 1950/23698
Progress: 2000/23698
Progress: 2050/23698
Progress: 2100/23698
Progress: 2150/23698
Progress: 2200/23698
Progress: 2250/23698
Progress: 2300/23698
Progress: 2350/23698
Progress: 2400/23698
Progress: 2450/23698
Progress: 2500/23698
Progress: 2550/23698
Progress: 2600/23698
Progress: 2650/23698
Progress: 2700/23698
Progress: 2750/23698
Progress: 2800/23698
Progress: 2850/23698
Progress: 2900/23698
Progress: 2950/23698
Progress: 3000/23698
Progress: 1900/23698
Progress: 1950/23698
Progress: 2000/23698
Progress: 2050/23698
Progress: 2100/23698
Progress: 2150/23698
Progress: 2200/23698
Progress: 2250/23698
Progress: 2300/23698
Progress: 2350/23698
Progress: 2400/23698
Progress: 2450/23698
Progress: 2500/23698
Progress: 2550/23698
Progress: 2600/23698
Progress: 2650/23698
Progress: 2700/23698
Progress: 2750/23698
Progress: 2800/23698
Progress: 2850/23698
Progress: 2900/23698
Progress: 2950/23698
Progress: 3000/23698
Progress: 3050/23698
Progress: 3100/23698
Progress: 3150/23698
Progress: 3200/23698
Progress: 3250/23698
Progress: 3300/23698
Progress: 3350/23698
Progress: 3050/23698
Progress: 3100/23698
Progress: 3150/23698
Progress: 3200/23698
Progress: 3250/23698
Progress: 3300/23698
Progress: 3350/23698
Progress: 3400/23698
Progress: 3450/23698
Progress: 3500/23698
Progress: 3550/23698
Progress: 3600/23698
Progress: 3650/23698
Progress: 3700/23698
Progress: 3750/23698
Progress: 3400/23698
Progress: 3450/23698
Progress: 3500/23698
Progress: 3550/23698
Progress: 3600/23698
Progress: 3650/23698
Progress: 3700/23698
Progress: 3750/23698
Progress: 3800/23698
Progress: 3850/23698
Progress: 3900/23698
Progress: 3950/23698
Progress: 4000/23698
Progress: 4050/23698
Progress: 3800/23698
Progress: 3850/23698
Progress: 3900/23698
Progress: 3950/23698
Progress: 4000/23698
Progress: 4050/23698
Progress: 4100/23698
Progress: 4150/23698
Progress: 4100/23698
Progress: 4150/23698
Progress: 4200/23698
Progress: 4250/23698
Progress: 4300/23698
Progress: 4200/23698
Progress: 4250/23698
Progress: 4300/23698
Progress: 4350/23698
Progress: 4350/23698
Progress: 4400/23698
Progress: 4450/23698
Progress: 4500/23698
Progress: 4550/23698
Progress: 4600/23698
Progress: 4650/23698
Progress: 4700/23698
Progress: 4750/23698
Progress: 4800/23698
Progress: 4400/23698
Progress: 4450/23698
Progress: 4500/23698
Progress: 4550/23698
Progress: 4600/23698
Progress: 4650/23698
Progress: 4700/23698
Progress: 4750/23698
Progress: 4800/23698
Progress: 4850/23698
Progress: 4900/23698
Progress: 4950/23698
Progress: 5000/23698
Progress: 5050/23698
Progress: 5100/23698
Progress: 5150/23698
Progress: 4850/23698
Progress: 4900/23698
Progress: 4950/23698
Progress: 5000/23698
Progress: 5050/23698
Progress: 5100/23698
Progress: 5150/23698
Progress: 5200/23698
Progress: 5250/23698
Progress: 5300/23698
Progress: 5350/23698
Progress: 5400/23698
Progress: 5200/23698
Progress: 5250/23698
Progress: 5300/23698
Progress: 5350/23698
Progress: 5400/23698
Progress: 5450/23698
Progress: 5500/23698
Progress: 5550/23698
Progress: 5600/23698
Progress: 5650/23698
Progress: 5700/23698
Progress: 5750/23698
Progress: 5800/23698
Progress: 5850/23698
Progress: 5900/23698
Progress: 5950/23698
Progress: 6000/23698
Progress: 6050/23698
Progress: 6100/23698
Progress: 6150/23698
Progress: 6200/23698
Progress: 6250/23698
Progress: 6300/23698
Progress: 6350/23698
Progress: 6400/23698
Progress: 5450/23698
Progress: 5500/23698
Progress: 5550/23698
Progress: 5600/23698
Progress: 5650/23698
Progress: 5700/23698
Progress: 5750/23698
Progress: 5800/23698
Progress: 5850/23698
Progress: 5900/23698
Progress: 5950/23698
Progress: 6000/23698
Progress: 6050/23698
Progress: 6100/23698
Progress: 6150/23698
Progress: 6200/23698
Progress: 6250/23698
Progress: 6300/23698
Progress: 6350/23698
Progress: 6400/23698
Progress: 6450/23698
Progress: 6450/23698
Progress: 6500/23698
Progress: 6550/23698
Progress: 6600/23698
Progress: 6650/23698
Progress: 6500/23698
Progress: 6550/23698
Progress: 6600/23698
Progress: 6650/23698
Progress: 6700/23698
Progress: 6750/23698
Progress: 6700/23698
Progress: 6750/23698
Progress: 6800/23698
Progress: 6850/23698
Progress: 6900/23698
Progress: 6950/23698
Progress: 7000/23698
Progress: 7050/23698
Progress: 7100/23698
Progress: 7150/23698
Progress: 7200/23698
Progress: 7250/23698
Progress: 7300/23698
Progress: 7350/23698
Progress: 7400/23698
Progress: 6800/23698
Progress: 6850/23698
Progress: 6900/23698
Progress: 6950/23698
Progress: 7000/23698
Progress: 7050/23698
Progress: 7100/23698
Progress: 7150/23698
Progress: 7200/23698
Progress: 7250/23698
Progress: 7300/23698
Progress: 7350/23698
Progress: 7400/23698
Progress: 7450/23698
Progress: 7500/23698
Progress: 7550/23698
Progress: 7600/23698
Progress: 7650/23698
Progress: 7700/23698
Progress: 7450/23698
Progress: 7500/23698
Progress: 7550/23698
Progress: 7600/23698
Progress: 7650/23698
Progress: 7700/23698
Progress: 7750/23698
Progress: 7800/23698
Progress: 7750/23698
Progress: 7800/23698
Progress: 7850/23698
Progress: 7850/23698
Progress: 7900/23698
Progress: 7950/23698
Progress: 8000/23698
Progress: 8050/23698
Progress: 8100/23698
Progress: 8150/23698
Progress: 8200/23698
Progress: 8250/23698
Progress: 8300/23698
Progress: 8350/23698
Progress: 8400/23698
Progress: 8450/23698
Progress: 8500/23698
Progress: 8550/23698
Progress: 8600/23698
Progress: 8650/23698
Progress: 8700/23698
Progress: 8750/23698
Progress: 8800/23698
Progress: 7900/23698
Progress: 7950/23698
Progress: 8000/23698
Progress: 8050/23698
Progress: 8100/23698
Progress: 8150/23698
Progress: 8200/23698
Progress: 8250/23698
Progress: 8300/23698
Progress: 8350/23698
Progress: 8400/23698
Progress: 8450/23698
Progress: 8500/23698
Progress: 8550/23698
Progress: 8600/23698
Progress: 8650/23698
Progress: 8700/23698
Progress: 8750/23698
Progress: 8800/23698
Progress: 8850/23698
Progress: 8850/23698
Progress: 8900/23698
Progress: 8950/23698
Progress: 9000/23698
Progress: 9050/23698
Progress: 9100/23698
Progress: 9150/23698
Progress: 9200/23698
Progress: 9250/23698
Progress: 9300/23698
Progress: 9350/23698
Progress: 9400/23698
Progress: 9450/23698
Progress: 9500/23698
Progress: 8900/23698
Progress: 8950/23698
Progress: 9000/23698
Progress: 9050/23698
Progress: 9100/23698
Progress: 9150/23698
Progress: 9200/23698
Progress: 9250/23698
Progress: 9300/23698
Progress: 9350/23698
Progress: 9400/23698
Progress: 9450/23698
Progress: 9500/23698
Progress: 9550/23698
Progress: 9600/23698
Progress: 9650/23698
Progress: 9700/23698
Progress: 9750/23698
Progress: 9800/23698
Progress: 9850/23698
Progress: 9900/23698
Progress: 9950/23698
Progress: 9550/23698
Progress: 9600/23698
Progress: 9650/23698
Progress: 9700/23698
Progress: 9750/23698
Progress: 9800/23698
Progress: 9850/23698
Progress: 9900/23698
Progress: 9950/23698
Progress: 10000/23698
Progress: 10050/23698
Progress: 10000/23698
Progress: 10050/23698
Progress: 10100/23698
Progress: 10150/23698
Progress: 10200/23698
Progress: 10250/23698
Progress: 10300/23698
Progress: 10350/23698
Progress: 10400/23698
Progress: 10450/23698
Progress: 10500/23698
Progress: 10550/23698
Progress: 10600/23698
Progress: 10100/23698
Progress: 10150/23698
Progress: 10200/23698
Progress: 10250/23698
Progress: 10300/23698
Progress: 10350/23698
Progress: 10400/23698
Progress: 10450/23698
Progress: 10500/23698
Progress: 10550/23698
Progress: 10600/23698
Progress: 10650/23698
Progress: 10700/23698
Progress: 10650/23698
Progress: 10700/23698
Progress: 10750/23698
Progress: 10750/23698
Progress: 10800/23698
Progress: 10850/23698
Progress: 10900/23698
Progress: 10950/23698
Progress: 11000/23698
Progress: 11050/23698
Progress: 11100/23698
Progress: 11150/23698
Progress: 11200/23698
Progress: 11250/23698
Progress: 11300/23698
Progress: 11350/23698
Progress: 11400/23698
Progress: 10800/23698
Progress: 10850/23698
Progress: 10900/23698
Progress: 10950/23698
Progress: 11000/23698
Progress: 11050/23698
Progress: 11100/23698
Progress: 11150/23698
Progress: 11200/23698
Progress: 11250/23698
Progress: 11300/23698
Progress: 11350/23698
Progress: 11400/23698
Progress: 11450/23698
Progress: 11450/23698
Progress: 11500/23698
Progress: 11550/23698
Progress: 11600/23698
Progress: 11650/23698
Progress: 11700/23698
Progress: 11750/23698
Progress: 11800/23698
Progress: 11500/23698
Progress: 11550/23698
Progress: 11600/23698
Progress: 11650/23698
Progress: 11700/23698
Progress: 11750/23698
Progress: 11800/23698
Progress: 11850/23698
Progress: 11900/23698
Progress: 11850/23698
Progress: 11900/23698
Progress: 11950/23698
Progress: 11950/23698
Progress: 12000/23698
Progress: 12000/23698
Progress: 12050/23698
Progress: 12100/23698
Progress: 12150/23698
Progress: 12200/23698
Progress: 12250/23698
Progress: 12300/23698
Progress: 12350/23698
Progress: 12050/23698
Progress: 12100/23698
Progress: 12150/23698
Progress: 12200/23698
Progress: 12250/23698
Progress: 12300/23698
Progress: 12350/23698
Progress: 12400/23698
Progress: 12450/23698
Progress: 12500/23698
Progress: 12400/23698
Progress: 12450/23698
Progress: 12500/23698
Progress: 12550/23698
Progress: 12600/23698
Progress: 12650/23698
Progress: 12550/23698
Progress: 12600/23698
Progress: 12650/23698
Progress: 12700/23698
Progress: 12700/23698
Progress: 12750/23698
Progress: 12800/23698
Progress: 12750/23698
Progress: 12800/23698
Progress: 12850/23698
Progress: 12900/23698
Progress: 12950/23698
Progress: 13000/23698
Progress: 13050/23698
Progress: 13100/23698
Progress: 12850/23698
Progress: 12900/23698
Progress: 12950/23698
Progress: 13000/23698
Progress: 13050/23698
Progress: 13100/23698
Progress: 13150/23698
Progress: 13200/23698
Progress: 13250/23698
Progress: 13150/23698
Progress: 13200/23698
Progress: 13250/23698
Progress: 13300/23698
Progress: 13300/23698
Progress: 13350/23698
Progress: 13400/23698
Progress: 13450/23698
Progress: 13500/23698
Progress: 13550/23698
Progress: 13350/23698
Progress: 13400/23698
Progress: 13450/23698
Progress: 13500/23698
Progress: 13550/23698
Progress: 13600/23698
Progress: 13650/23698
Progress: 13700/23698
Progress: 13600/23698
Progress: 13650/23698
Progress: 13700/23698
Progress: 13750/23698
Progress: 13750/23698
Progress: 13800/23698
Progress: 13850/23698
Progress: 13900/23698
Progress: 13950/23698
Progress: 14000/23698
Progress: 14050/23698
Progress: 14100/23698
Progress: 14150/23698
Progress: 14200/23698
Progress: 14250/23698
Progress: 14300/23698
Progress: 14350/23698
Progress: 14400/23698
Progress: 14450/23698
Progress: 13800/23698
Progress: 13850/23698
Progress: 13900/23698
Progress: 13950/23698
Progress: 14000/23698
Progress: 14050/23698
Progress: 14100/23698
Progress: 14150/23698
Progress: 14200/23698
Progress: 14250/23698
Progress: 14300/23698
Progress: 14350/23698
Progress: 14400/23698
Progress: 14450/23698
Progress: 14500/23698
Progress: 14550/23698
Progress: 14500/23698
Progress: 14550/23698
Progress: 14600/23698
Progress: 14650/23698
Progress: 14700/23698
Progress: 14750/23698
Progress: 14800/23698
Progress: 14600/23698
Progress: 14650/23698
Progress: 14700/23698
Progress: 14750/23698
Progress: 14800/23698
Progress: 14850/23698
Progress: 14900/23698
Progress: 14950/23698
Progress: 15000/23698
Progress: 15050/23698
Progress: 15100/23698
Progress: 15150/23698
Progress: 14850/23698
Progress: 14900/23698
Progress: 14950/23698
Progress: 15000/23698
Progress: 15050/23698
Progress: 15100/23698
Progress: 15150/23698
Progress: 15200/23698
Progress: 15200/23698
Progress: 15250/23698
Progress: 15300/23698
Progress: 15350/23698
Progress: 15400/23698
Progress: 15450/23698
Progress: 15500/23698
Progress: 15550/23698
Progress: 15250/23698
Progress: 15300/23698
Progress: 15350/23698
Progress: 15400/23698
Progress: 15450/23698
Progress: 15500/23698
Progress: 15550/23698
Progress: 15600/23698
Progress: 15650/23698
Progress: 15600/23698
Progress: 15650/23698
Progress: 15700/23698
Progress: 15750/23698
Progress: 15800/23698
Progress: 15850/23698
Progress: 15900/23698
Progress: 15950/23698
Progress: 16000/23698
Progress: 16050/23698
Progress: 16100/23698
Progress: 16150/23698
Progress: 16200/23698
Progress: 16250/23698
Progress: 16300/23698
Progress: 16350/23698
Progress: 16400/23698
Progress: 16450/23698
Progress: 16500/23698
Progress: 16550/23698
Progress: 15700/23698
Progress: 15750/23698
Progress: 15800/23698
Progress: 15850/23698
Progress: 15900/23698
Progress: 15950/23698
Progress: 16000/23698
Progress: 16050/23698
Progress: 16100/23698
Progress: 16150/23698
Progress: 16200/23698
Progress: 16250/23698
Progress: 16300/23698
Progress: 16350/23698
Progress: 16400/23698
Progress: 16450/23698
Progress: 16500/23698
Progress: 16550/23698
Progress: 16600/23698
Progress: 16650/23698
Progress: 16700/23698
Progress: 16750/23698
Progress: 16800/23698
Progress: 16850/23698
Progress: 16600/23698
Progress: 16650/23698
Progress: 16700/23698
Progress: 16750/23698
Progress: 16800/23698
Progress: 16850/23698
Progress: 16900/23698
Progress: 16950/23698
Progress: 17000/23698
Progress: 17050/23698
Progress: 17100/23698
Progress: 17150/23698
Progress: 17200/23698
Progress: 16900/23698
Progress: 16950/23698
Progress: 17000/23698
Progress: 17050/23698
Progress: 17100/23698
Progress: 17150/23698
Progress: 17200/23698
Progress: 17250/23698
Progress: 17300/23698
Progress: 17250/23698
Progress: 17300/23698
Progress: 17350/23698
Progress: 17400/23698
Progress: 17450/23698
Progress: 17500/23698
Progress: 17550/23698
Progress: 17350/23698
Progress: 17400/23698
Progress: 17450/23698
Progress: 17500/23698
Progress: 17550/23698
Progress: 17600/23698
Progress: 17650/23698
Progress: 17600/23698
Progress: 17650/23698
Progress: 17700/23698
Progress: 17750/23698
Progress: 17800/23698
Progress: 17850/23698
Progress: 17900/23698
Progress: 17700/23698
Progress: 17750/23698
Progress: 17800/23698
Progress: 17850/23698
Progress: 17900/23698
Progress: 17950/23698
Progress: 17950/23698
Progress: 18000/23698
Progress: 18000/23698
Progress: 18050/23698
Progress: 18100/23698
Progress: 18150/23698
Progress: 18200/23698
Progress: 18250/23698
Progress: 18300/23698
Progress: 18350/23698
Progress: 18400/23698
Progress: 18450/23698
Progress: 18500/23698
Progress: 18550/23698
Progress: 18600/23698
Progress: 18650/23698
Progress: 18050/23698
Progress: 18100/23698
Progress: 18150/23698
Progress: 18200/23698
Progress: 18250/23698
Progress: 18300/23698
Progress: 18350/23698
Progress: 18400/23698
Progress: 18450/23698
Progress: 18500/23698
Progress: 18550/23698
Progress: 18600/23698
Progress: 18650/23698
Progress: 18700/23698
Progress: 18700/23698
Progress: 18750/23698
Progress: 18800/23698
Progress: 18850/23698
Progress: 18900/23698
Progress: 18950/23698
Progress: 19000/23698
Progress: 19050/23698
Progress: 19100/23698
Progress: 18750/23698
Progress: 18800/23698
Progress: 18850/23698
Progress: 18900/23698
Progress: 18950/23698
Progress: 19000/23698
Progress: 19050/23698
Progress: 19100/23698
Error (MP) processing 1gkm A CYS: 'A'
Error (MP) processing 1gkm A CYS: 'A'
Progress: 19150/23698
Progress: 19200/23698
Progress: 19250/23698
Progress: 19150/23698
Progress: 19200/23698
Progress: 19250/23698
Progress: 19300/23698
Progress: 19350/23698
Progress: 19400/23698
Progress: 19450/23698
Progress: 19500/23698
Progress: 19550/23698
Progress: 19600/23698
Progress: 19300/23698
Progress: 19350/23698
Progress: 19400/23698
Progress: 19450/23698
Progress: 19500/23698
Progress: 19550/23698
Progress: 19600/23698
Progress: 19650/23698
Progress: 19700/23698
Progress: 19750/23698
Progress: 19800/23698
Progress: 19850/23698
Progress: 19900/23698
Progress: 19950/23698
Progress: 20000/23698
Progress: 20050/23698
Progress: 20100/23698
Progress: 20150/23698
Progress: 20200/23698
Progress: 20250/23698
Progress: 20300/23698
Progress: 19650/23698
Progress: 19700/23698
Progress: 19750/23698
Progress: 19800/23698
Progress: 19850/23698
Progress: 19900/23698
Progress: 19950/23698
Progress: 20000/23698
Progress: 20050/23698
Progress: 20100/23698
Progress: 20150/23698
Progress: 20200/23698
Progress: 20250/23698
Progress: 20300/23698
Progress: 20350/23698
Progress: 20400/23698
Progress: 20450/23698
Progress: 20500/23698
Progress: 20550/23698
Progress: 20600/23698
Progress: 20650/23698
Progress: 20700/23698
Progress: 20350/23698
Progress: 20400/23698
Progress: 20450/23698
Progress: 20500/23698
Progress: 20550/23698
Progress: 20600/23698
Progress: 20650/23698
Progress: 20700/23698
Progress: 20750/23698
Progress: 20800/23698
Progress: 20850/23698
Progress: 20900/23698
Progress: 20950/23698
Progress: 21000/23698
Progress: 21050/23698
Progress: 21100/23698
Progress: 21150/23698
Progress: 21200/23698
Progress: 21250/23698
Progress: 21300/23698
Progress: 21350/23698
Progress: 21400/23698
Progress: 21450/23698
Progress: 21500/23698
Progress: 21550/23698
Progress: 20750/23698
Progress: 20800/23698
Progress: 20850/23698
Progress: 20900/23698
Progress: 20950/23698
Progress: 21000/23698
Progress: 21050/23698
Progress: 21100/23698
Progress: 21150/23698
Progress: 21200/23698
Progress: 21250/23698
Progress: 21300/23698
Progress: 21350/23698
Progress: 21400/23698
Progress: 21450/23698
Progress: 21500/23698
Progress: 21550/23698
Progress: 21600/23698
Progress: 21650/23698
Progress: 21700/23698
Progress: 21750/23698
Progress: 21800/23698
Progress: 21850/23698
Progress: 21900/23698
Progress: 21950/23698
Progress: 21600/23698
Progress: 21650/23698
Progress: 21700/23698
Progress: 21750/23698
Progress: 21800/23698
Progress: 21850/23698
Progress: 21900/23698
Progress: 21950/23698
Progress: 22000/23698
Progress: 22050/23698
Progress: 22100/23698
Progress: 22000/23698
Progress: 22050/23698
Progress: 22100/23698
Progress: 22150/23698
Progress: 22200/23698
Progress: 22250/23698
Progress: 22150/23698
Progress: 22200/23698
Progress: 22250/23698
Progress: 22300/23698
Progress: 22350/23698
Progress: 22400/23698
Progress: 22450/23698
Progress: 22500/23698
Progress: 22550/23698
Progress: 22600/23698
Progress: 22650/23698
Progress: 22700/23698
Progress: 22300/23698
Progress: 22350/23698
Progress: 22400/23698
Progress: 22450/23698
Progress: 22500/23698
Progress: 22550/23698
Progress: 22600/23698
Progress: 22650/23698
Progress: 22700/23698
Progress: 22750/23698
Progress: 22750/23698
Progress: 22800/23698
Progress: 22800/23698
Progress: 22850/23698
Progress: 22900/23698
Progress: 22950/23698
Progress: 23000/23698
Progress: 23050/23698
Progress: 23100/23698

Failed to parse the downloaded structure 8bd3: The input mmCIF file must begin with a 'data_' directive.

Error (MP) processing 8bd3 m CLA: 0

Progress: 23150/23698
Progress: 23200/23698
Progress: 23150/23698
Progress: 23200/23698
Progress: 23250/23698
Progress: 23300/23698
Progress: 23350/23698
Progress: 23400/23698
Progress: 23450/23698
Progress: 23500/23698
Progress: 23550/23698
Progress: 23600/23698
Progress: 23650/23698
Progress: 23250/23698
Progress: 23300/23698
Progress: 23350/23698
Progress: 23400/23698
Progress: 23450/23698
Progress: 23500/23698
Progress: 23550/23698
Progress: 23600/23698
Progress: 23650/23698

Completed! Added pocket_residue_ids, tar_motif, num_ligand_residues. Multi-residue cases: 5189
Sample row: tar_ligand                                                           ASN
tar_protein                                                         11as
tar_chain                                                              A
tar_motif              [45, 46, 48, 49, 50, 52, 72, 74, 75, 77, 100, ...
pocket_residue_ids     [45, 46, 48, 49, 50, 52, 72, 74, 75, 77, 100, ...
num_ligand_residues                                                    4
Name: 0, dtype: object

Completed! Added pocket_residue_ids, tar_motif, num_ligand_residues. Multi-residue cases: 5189
Sample row: tar_ligand                                                           ASN
tar_protein                                                         11as
tar_chain                                                              A
tar_motif              [45, 46, 48, 49, 50, 52, 72, 74, 75, 77, 100, ...
pocket_residue_ids     [45, 46, 48, 49, 50, 52, 72, 74, 75, 77, 100, ...
num_ligand_residues                                                    4
Name: 0, dtype: object

In [ ]:
# Save the final dataframe with pocket residue IDs

# Ensure tar_motif column entries are lists (or None)
df_nr['tar_motif'] = df_nr['tar_motif'].apply(lambda x: x if (x is None or isinstance(x, list)) else [x])

df_nr = df_nr.drop(columns=['pocket_residue_ids'])

# save full
df_nr.to_csv('../example_inputs/biolip2_nr_database_with_motif.csv', index=False)
print("✅ Saved df_nr with pocket residue IDs and tar_motif lists to 'biolip2_nr_database_with_motif.csv'")

# save mini
df_nr.head(50).to_csv('../example_inputs/biolip2_nr_mini_database_with_motif.csv', index=False)
print("✅ Saved df_nr mini to 'biolip2_nr_mini_database_with_motif.csv'")

print(f"\nDataframe shape: {df_nr.shape}")
print(f"Columns: {list(df_nr.columns)}")
print("tar_motif types:", df_nr['tar_motif'].apply(lambda x: type(x).__name__).value_counts().to_dict())
print(f"\nFirst few rows:")
df_nr.head()

✅ Saved df_nr with pocket residue IDs and tar_motif lists to 'biolip2_nr_database_with_motif.csv'
✅ Saved df_nr mini to 'biolip2_nr_mini_database_with_motif.csv'

Dataframe shape: (23698, 5)
Columns: ['tar_ligand', 'tar_protein', 'tar_chain', 'tar_motif', 'num_ligand_residues']
tar_motif types: {'list': 21748, 'NoneType': 1950}

First few rows:

,tar_ligand,tar_protein,tar_chain,tar_motif,num_ligand_residues
0,ASN,11as,A,"[45, 46, 48, 49, 50, 52, 72, 74, 75, 77, 100, ...",4
1,UPA,11ba,A,"[41, 43, 44, 45, 65, 67, 69, 71, 109, 118, 119...",1
2,ADP,13pk,A,"[217, 218, 219, 223, 241, 242, 245, 294, 314, ...",1
3,HEM,19hc,A,"[8, 10, 11, 14, 16, 17, 18, 29, 30, 31, 32, 33...",9
4,IPM,1a05,A,"[88, 95, 105, 133, 140, 246, 501, 524, 553, 56...",1

In [ ]:
'''
Manual fixes:
1gkm_A => 1gkm_B                                                                                                 | 1/8 [00:11<01:19, 11.33s/it]Failed to download 4ct3 chain A ligand general: 'A'
4ct3_A => 4ct3_E
2h8p_D => delete
'''

In [ ]:
# create mini